/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type Gallery = Array<{
  _key: string;
} & ImageAlt | {
  _key: string;
} & MuxVideo>;

export type ShowReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "show";
};

export type PodcastReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "podcast";
};

export type ResearchReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "research";
};

export type TransmissionReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "transmission";
};

export type MemberReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "member";
};

export type CustomBlock = Array<{
  children?: Array<{
    marks?: Array<string>;
    text?: string;
    _type: "span";
    _key: string;
  }>;
  style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
  listItem?: "bullet" | "number";
  markDefs?: Array<{
    href?: string;
    _type: "link";
    _key: string;
  } | ShowReference | PodcastReference | ResearchReference | TransmissionReference | MemberReference>;
  level?: number;
  _type: "block";
  _key: string;
}>;

export type Seasons = Array<{
  range: string;
  events: Array<{
    title: string;
    description?: string;
    date?: string;
    place?: string;
    link?: string;
    project?: ShowReference | PodcastReference | ResearchReference | TransmissionReference;
    _key: string;
  }>;
  _type: "season";
  _key: string;
}>;

export type LinksArray = Array<{
  title: string;
  subtitle?: string;
  url: string;
  _key: string;
}>;

export type JobReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "job";
};

export type Credits = Array<{
  title?: JobReference;
  value?: Array<{
    _key: string;
  } & MemberReference | {
    value: CustomBlock;
    _type: "personText";
    _key: string;
  }>;
  _key: string;
}>;

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type ImageAlt = {
  _type: "imageAlt";
  asset?: SanityImageAssetReference;
  media?: unknown;
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  alt: string;
};

export type Favicon = {
  _type: "favicon";
  asset?: SanityImageAssetReference;
  media?: unknown;
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
};

export type Legal = {
  _id: string;
  _type: "legal";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  content: CustomBlock;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type Member = {
  _id: string;
  _type: "member";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  slug: Slug;
  role: string;
  link?: string;
  presentation?: CustomBlock;
};

export type Team = {
  _id: string;
  _type: "team";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  members?: Array<{
    _key: string;
  } & MemberReference>;
};

export type Calendar = {
  _id: string;
  _type: "calendar";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  introduction?: CustomBlock;
  seasons?: Seasons;
};

export type Company = {
  _id: string;
  _type: "company";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  presentation: CustomBlock;
  seasons?: Seasons;
};

export type Transmission = {
  _id: string;
  _type: "transmission";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  introduction: CustomBlock;
  seasons?: Seasons;
};

export type Podcast = {
  _id: string;
  _type: "podcast";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  date: string;
  cover: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    orientation?: "landscape" | "portrait";
    _type: "image";
  };
  synopsis: CustomBlock;
  episodes?: Array<{
    title: string;
    mp3?: MuxVideo;
    _type: "episode";
    _key: string;
  }>;
  infos?: CustomBlock;
  supports?: string;
  production?: string;
  credits?: Credits;
  gallery?: Gallery;
  links?: LinksArray;
  press?: LinksArray;
};

export type MuxVideoAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "mux.videoAsset";
};

export type MuxVideo = {
  _type: "mux.video";
  asset?: MuxVideoAssetReference;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type Show = {
  _id: string;
  _type: "show";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  date: string;
  cover: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    orientation?: "landscape" | "portrait";
    _type: "image";
  };
  synopsis: CustomBlock;
  excerpt?: string;
  infos?: CustomBlock;
  supports?: string;
  production?: string;
  credits?: Credits;
  gallery?: Gallery;
  links?: LinksArray;
  press?: LinksArray;
};

export type Job = {
  _id: string;
  _type: "job";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
};

export type Research = {
  _id: string;
  _type: "research";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  presentation: CustomBlock;
  notes?: CustomBlock;
  excerptTitle?: string;
  excerpt?: CustomBlock;
};

export type Settings = {
  _id: string;
  _type: "settings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  description: string;
  favicon?: {
    dark: Favicon;
    light: Favicon;
  };
  homeImage: ImageAlt;
  navigation: Array<{
    title: string;
    slug: Slug;
    _type: "item";
    _key: string;
  }>;
};

export type MuxVideoAsset = {
  _id: string;
  _type: "mux.videoAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  status?: string;
  assetId?: string;
  playbackId?: string;
  filename?: string;
  thumbTime?: number;
  data?: MuxAssetData;
};

export type MuxAssetData = {
  _type: "mux.assetData";
  resolution_tier?: string;
  upload_id?: string;
  created_at?: string;
  id?: string;
  status?: string;
  max_stored_resolution?: string;
  passthrough?: string;
  encoding_tier?: string;
  video_quality?: string;
  master_access?: string;
  aspect_ratio?: string;
  duration?: number;
  max_stored_frame_rate?: number;
  mp4_support?: string;
  max_resolution_tier?: string;
  tracks?: Array<{
    _key: string;
  } & MuxTrack>;
  playback_ids?: Array<{
    _key: string;
  } & MuxPlaybackId>;
  static_renditions?: MuxStaticRenditions;
};

export type MuxStaticRenditions = {
  _type: "mux.staticRenditions";
  status?: string;
  files?: Array<{
    _key: string;
  } & MuxStaticRenditionFile>;
};

export type MuxStaticRenditionFile = {
  _type: "mux.staticRenditionFile";
  name?: string;
  ext?: string;
  height?: number;
  width?: number;
  bitrate?: number;
  filesize?: string;
  type?: string;
  status?: string;
  resolution_tier?: string;
  resolution?: string;
  id?: string;
  passthrough?: string;
};

export type MuxPlaybackId = {
  _type: "mux.playbackId";
  id?: string;
  policy?: string;
};

export type MuxTrack = {
  _type: "mux.track";
  id?: string;
  type?: string;
  max_width?: number;
  max_frame_rate?: number;
  duration?: number;
  max_height?: number;
  language_code?: string;
  name?: string;
  status?: string;
  text_source?: string;
  text_type?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes = Gallery | ShowReference | PodcastReference | ResearchReference | TransmissionReference | MemberReference | CustomBlock | Seasons | LinksArray | JobReference | Credits | SanityImageAssetReference | ImageAlt | Favicon | Legal | Slug | Member | Team | Calendar | Company | Transmission | Podcast | MuxVideoAssetReference | MuxVideo | SanityImageCrop | SanityImageHotspot | Show | Job | Research | Settings | MuxVideoAsset | MuxAssetData | MuxStaticRenditions | MuxStaticRenditionFile | MuxPlaybackId | MuxTrack | SanityImagePaletteSwatch | SanityImagePalette | SanityImageDimensions | SanityImageMetadata | SanityFileAsset | SanityAssetSourceData | SanityImageAsset | Geopoint;

// Source: src/sanity/lib/queries.ts
// Variable: layoutSettingsQuery
// Query: *[_type == "settings"][0]{    title,    description,    "favicons": favicon{      "light": light.asset->url,      "dark": dark.asset->url,    }  }
export type LayoutSettingsQueryResult = {
  title: string;
  description: string;
  favicons: {
    light: string | null;
    dark: string | null;
  } | null;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: footerSettingsQuery
// Query: *[_type == "settings"][0]{    title,    "navigation": navigation[]{      title,      "slug": slug.current    },    "navigationLogo": favicon.dark.asset->url,  }
export type FooterSettingsQueryResult = {
  title: string;
  navigation: Array<{
    title: string;
    slug: string;
  }>;
  navigationLogo: string | null;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: homeImageQuery
// Query: *[_type == "settings"  && defined(homeImage.asset->url)][0].homeImage{  "src": coalesce(asset->url, ""),  "alt": coalesce(alt, ^.title, ""),  crop,  hotspot,}
export type HomeImageQueryResult = {
  src: string | "";
  alt: string;
  crop: SanityImageCrop | null;
  hotspot: SanityImageHotspot | null;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: showsListQuery
// Query: *[_type == "show"]{  title,  "slug": slug.current,  date,  "cover": cover{    "src": coalesce(asset->url, ""),    "orientation": coalesce(orientation, "landscape"),    crop,    hotspot,  },} | order(date desc)
export type ShowsListQueryResult = Array<{
  title: string;
  slug: string;
  date: string;
  cover: {
    src: string | "";
    orientation: "landscape" | "portrait";
    crop: SanityImageCrop | null;
    hotspot: SanityImageHotspot | null;
  };
}>;

// Source: src/sanity/lib/queries.ts
// Variable: showBySlugQuery
// Query: *[_type == "show" && slug.current == $slug][0]{    title,    "slug": slug.current,    date,    "synopsis": synopsis[]{  ...,  markDefs[]{    ...,    _type == "internalLink" => {      ...,      "slug": *[_id == ^._ref][0].slug.current,      "refType": *[_id == ^._ref][0]._type    }  }},    excerpt,    "infos": infos[]{  ...,  markDefs[]{    ...,    _type == "internalLink" => {      ...,      "slug": *[_id == ^._ref][0].slug.current,      "refType": *[_id == ^._ref][0]._type    }  }},    supports,    production,    "credits": credits[]{  "title": title->title,  "value": value[]{    _type == "reference" => @->{      _type,      "name": name,      "slug": slug.current,      "link": link,    },    _type != "reference" => @{      _type,      "text": value,    },  },},    "gallery": gallery[]{  _type,  _type == "imageAlt" => {  "src": coalesce(asset->url, ""),  "alt": coalesce(alt, ^.title, ""),  crop,  hotspot,},  _type == "mux.video" => {    "playbackId": coalesce(asset->playbackId, ""),  }},    links,    press  }
export type ShowBySlugQueryResult = {
  title: string;
  slug: string;
  date: string;
  synopsis: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs: Array<{
      href?: string;
      _type: "link";
      _key: string;
    } | {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
    }> | null;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  excerpt: string | null;
  infos: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs: Array<{
      href?: string;
      _type: "link";
      _key: string;
    } | {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
    }> | null;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  supports: string | null;
  production: string | null;
  credits: Array<{
    title: string | null;
    value: Array<{
      _type: "member";
      name: string;
      slug: string;
      link: string | null;
    } | {
      _type: "personText";
      text: CustomBlock;
    }> | null;
  }> | null;
  gallery: Array<{
    _type: "imageAlt";
    src: string | "";
    alt: string;
    crop: SanityImageCrop | null;
    hotspot: SanityImageHotspot | null;
  } | {
    _type: "mux.video";
    playbackId: string | "";
  }> | null;
  links: LinksArray | null;
  press: LinksArray | null;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: podcastsListQuery
// Query: *[_type == "podcast"]{  title,  "slug": slug.current,  date,  "cover": cover{    "src": coalesce(asset->url, ""),    "orientation": coalesce(orientation, "landscape"),    crop,    hotspot,  },} | order(date desc)
export type PodcastsListQueryResult = Array<{
  title: string;
  slug: string;
  date: string;
  cover: {
    src: string | "";
    orientation: "landscape" | "portrait";
    crop: SanityImageCrop | null;
    hotspot: SanityImageHotspot | null;
  };
}>;

// Source: src/sanity/lib/queries.ts
// Variable: podcastBySlugQuery
// Query: *[_type == "podcast" && slug.current == $slug][0]{    title,    "slug": slug.current,    date,    "synopsis": synopsis[]{  ...,  markDefs[]{    ...,    _type == "internalLink" => {      ...,      "slug": *[_id == ^._ref][0].slug.current,      "refType": *[_id == ^._ref][0]._type    }  }},    "episodes": episodes[]{      title,      "playbackId": mp3.asset->playbackId,    },    "infos": infos[]{  ...,  markDefs[]{    ...,    _type == "internalLink" => {      ...,      "slug": *[_id == ^._ref][0].slug.current,      "refType": *[_id == ^._ref][0]._type    }  }},    supports,    production,    "credits": credits[]{  "title": title->title,  "value": value[]{    _type == "reference" => @->{      _type,      "name": name,      "slug": slug.current,      "link": link,    },    _type != "reference" => @{      _type,      "text": value,    },  },},    "gallery": gallery[]{  _type,  _type == "imageAlt" => {  "src": coalesce(asset->url, ""),  "alt": coalesce(alt, ^.title, ""),  crop,  hotspot,},  _type == "mux.video" => {    "playbackId": coalesce(asset->playbackId, ""),  }},    links,    press  }
export type PodcastBySlugQueryResult = {
  title: string;
  slug: string;
  date: string;
  synopsis: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs: Array<{
      href?: string;
      _type: "link";
      _key: string;
    } | {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
    }> | null;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  episodes: Array<{
    title: string;
    playbackId: string | null;
  }> | null;
  infos: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs: Array<{
      href?: string;
      _type: "link";
      _key: string;
    } | {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
    }> | null;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  supports: string | null;
  production: string | null;
  credits: Array<{
    title: string | null;
    value: Array<{
      _type: "member";
      name: string;
      slug: string;
      link: string | null;
    } | {
      _type: "personText";
      text: CustomBlock;
    }> | null;
  }> | null;
  gallery: Array<{
    _type: "imageAlt";
    src: string | "";
    alt: string;
    crop: SanityImageCrop | null;
    hotspot: SanityImageHotspot | null;
  } | {
    _type: "mux.video";
    playbackId: string | "";
  }> | null;
  links: LinksArray | null;
  press: LinksArray | null;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: researchQuery
// Query: *[_type == "research"][0]{  title,  "presentation": presentation[]{  ...,  markDefs[]{    ...,    _type == "internalLink" => {      ...,      "slug": *[_id == ^._ref][0].slug.current,      "refType": *[_id == ^._ref][0]._type    }  }},  "notes": notes[]{  ...,  markDefs[]{    ...,    _type == "internalLink" => {      ...,      "slug": *[_id == ^._ref][0].slug.current,      "refType": *[_id == ^._ref][0]._type    }  }},  excerptTitle,  "excerpt": excerpt[]{  ...,  markDefs[]{    ...,    _type == "internalLink" => {      ...,      "slug": *[_id == ^._ref][0].slug.current,      "refType": *[_id == ^._ref][0]._type    }  }}}
export type ResearchQueryResult = {
  title: string;
  presentation: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs: Array<{
      href?: string;
      _type: "link";
      _key: string;
    } | {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
    }> | null;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  notes: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs: Array<{
      href?: string;
      _type: "link";
      _key: string;
    } | {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
    }> | null;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  excerptTitle: string | null;
  excerpt: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs: Array<{
      href?: string;
      _type: "link";
      _key: string;
    } | {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
    }> | null;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: teamQuery
// Query: *[_type == "team"][0]{  title,  "members": members[]->{    name,    slug,    role,    link,    "presentation": presentation[]{  ...,  markDefs[]{    ...,    _type == "internalLink" => {      ...,      "slug": *[_id == ^._ref][0].slug.current,      "refType": *[_id == ^._ref][0]._type    }  }}  }}
export type TeamQueryResult = {
  title: string;
  members: Array<{
    name: string;
    slug: Slug;
    role: string;
    link: string | null;
    presentation: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
      listItem?: "bullet" | "number";
      markDefs: Array<{
        href?: string;
        _type: "link";
        _key: string;
      } | {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
      }> | null;
      level?: number;
      _type: "block";
      _key: string;
    }> | null;
  }> | null;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: calendarQuery
// Query: *[_type == "calendar"][0]{  title,  "introduction": introduction[]{  ...,  markDefs[]{    ...,    _type == "internalLink" => {      ...,      "slug": *[_id == ^._ref][0].slug.current,      "refType": *[_id == ^._ref][0]._type    }  }},    "seasons": seasons[]{    range,    "events": events[]{      title,      description,      date,      place,      link,      "project": project->{        title,        "slug": slug.current,        _type,      }    }  }}
export type CalendarQueryResult = {
  title: string;
  introduction: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs: Array<{
      href?: string;
      _type: "link";
      _key: string;
    } | {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
    }> | null;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  seasons: Array<{
    range: string;
    events: Array<{
      title: string;
      description: string | null;
      date: string | null;
      place: string | null;
      link: string | null;
      project: {
        title: string;
        slug: string;
        _type: "podcast";
      } | {
        title: string;
        slug: null;
        _type: "research";
      } | {
        title: string;
        slug: string;
        _type: "show";
      } | {
        title: string;
        slug: null;
        _type: "transmission";
      } | null;
    }>;
  }> | null;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: transmissionQuery
// Query: *[_type == "transmission"][0]{  title,  "introduction": introduction[]{  ...,  markDefs[]{    ...,    _type == "internalLink" => {      ...,      "slug": *[_id == ^._ref][0].slug.current,      "refType": *[_id == ^._ref][0]._type    }  }},    "seasons": seasons[]{    range,    "events": events[]{      title,      description,      date,      place,      link,      "project": project->{        title,        "slug": slug.current,        _type,      }    }  }}
export type TransmissionQueryResult = {
  title: string;
  introduction: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs: Array<{
      href?: string;
      _type: "link";
      _key: string;
    } | {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
    }> | null;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  seasons: Array<{
    range: string;
    events: Array<{
      title: string;
      description: string | null;
      date: string | null;
      place: string | null;
      link: string | null;
      project: {
        title: string;
        slug: string;
        _type: "podcast";
      } | {
        title: string;
        slug: null;
        _type: "research";
      } | {
        title: string;
        slug: string;
        _type: "show";
      } | {
        title: string;
        slug: null;
        _type: "transmission";
      } | null;
    }>;
  }> | null;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: companyQuery
// Query: *[_type == "company"][0]{  title,  "presentation": presentation[]{  ...,  markDefs[]{    ...,    _type == "internalLink" => {      ...,      "slug": *[_id == ^._ref][0].slug.current,      "refType": *[_id == ^._ref][0]._type    }  }},    "seasons": seasons[]{    range,    "events": events[]{      title,      description,      date,      place,      link,      "project": project->{        title,        "slug": slug.current,        _type,      }    }  }}
export type CompanyQueryResult = {
  title: string;
  presentation: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs: Array<{
      href?: string;
      _type: "link";
      _key: string;
    } | {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
    }> | null;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  seasons: Array<{
    range: string;
    events: Array<{
      title: string;
      description: string | null;
      date: string | null;
      place: string | null;
      link: string | null;
      project: {
        title: string;
        slug: string;
        _type: "podcast";
      } | {
        title: string;
        slug: null;
        _type: "research";
      } | {
        title: string;
        slug: string;
        _type: "show";
      } | {
        title: string;
        slug: null;
        _type: "transmission";
      } | null;
    }>;
  }> | null;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: pagesListQuery
// Query: *[_type == "legal"]{  "slug": slug.current}
export type PagesListQueryResult = Array<{
  slug: string;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: pageBySlugQuery
// Query: *[_type == "legal" && slug.current == $slug][0]{  title,  "slug": slug.current,  "content": content[]{  ...,  markDefs[]{    ...,    _type == "internalLink" => {      ...,      "slug": *[_id == ^._ref][0].slug.current,      "refType": *[_id == ^._ref][0]._type    }  }}}
export type PageBySlugQueryResult = {
  title: string;
  slug: string;
  content: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs: Array<{
      href?: string;
      _type: "link";
      _key: string;
    } | {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
    }> | null;
    level?: number;
    _type: "block";
    _key: string;
  }>;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    "*[_type == \"settings\"][0]{\n    title,\n    description,\n    \"favicons\": favicon{\n      \"light\": light.asset->url,\n      \"dark\": dark.asset->url,\n    }\n  }": LayoutSettingsQueryResult;
    "*[_type == \"settings\"][0]{\n    title,\n    \"navigation\": navigation[]{\n      title,\n      \"slug\": slug.current\n    },\n    \"navigationLogo\": favicon.dark.asset->url,\n  }": FooterSettingsQueryResult;
    "*[_type == \"settings\"\n  && defined(homeImage.asset->url)][0].homeImage{\n  \"src\": coalesce(asset->url, \"\"),\n  \"alt\": coalesce(alt, ^.title, \"\"),\n  crop,\n  hotspot,\n}": HomeImageQueryResult;
    "*[_type == \"show\"]{\n  title,\n  \"slug\": slug.current,\n  date,\n  \"cover\": cover{\n    \"src\": coalesce(asset->url, \"\"),\n    \"orientation\": coalesce(orientation, \"landscape\"),\n    crop,\n    hotspot,\n  },\n} | order(date desc)": ShowsListQueryResult;
    "*[_type == \"show\" && slug.current == $slug][0]{\n    title,\n    \"slug\": slug.current,\n    date,\n    \"synopsis\": synopsis[]{\n  ...,\n  markDefs[]{\n    ...,\n    _type == \"internalLink\" => {\n      ...,\n      \"slug\": *[_id == ^._ref][0].slug.current,\n      \"refType\": *[_id == ^._ref][0]._type\n    }\n  }\n},\n    excerpt,\n    \"infos\": infos[]{\n  ...,\n  markDefs[]{\n    ...,\n    _type == \"internalLink\" => {\n      ...,\n      \"slug\": *[_id == ^._ref][0].slug.current,\n      \"refType\": *[_id == ^._ref][0]._type\n    }\n  }\n},\n    supports,\n    production,\n    \"credits\": credits[]{\n  \"title\": title->title,\n  \"value\": value[]{\n    _type == \"reference\" => @->{\n      _type,\n      \"name\": name,\n      \"slug\": slug.current,\n      \"link\": link,\n    },\n    _type != \"reference\" => @{\n      _type,\n      \"text\": value,\n    },\n  },\n},\n    \"gallery\": gallery[]{\n  _type,\n  _type == \"imageAlt\" => {\n  \"src\": coalesce(asset->url, \"\"),\n  \"alt\": coalesce(alt, ^.title, \"\"),\n  crop,\n  hotspot,\n},\n  _type == \"mux.video\" => {\n    \"playbackId\": coalesce(asset->playbackId, \"\"),\n  }\n},\n    links,\n    press\n  }\n": ShowBySlugQueryResult;
    "*[_type == \"podcast\"]{\n  title,\n  \"slug\": slug.current,\n  date,\n  \"cover\": cover{\n    \"src\": coalesce(asset->url, \"\"),\n    \"orientation\": coalesce(orientation, \"landscape\"),\n    crop,\n    hotspot,\n  },\n} | order(date desc)": PodcastsListQueryResult;
    "*[_type == \"podcast\" && slug.current == $slug][0]{\n    title,\n    \"slug\": slug.current,\n    date,\n    \"synopsis\": synopsis[]{\n  ...,\n  markDefs[]{\n    ...,\n    _type == \"internalLink\" => {\n      ...,\n      \"slug\": *[_id == ^._ref][0].slug.current,\n      \"refType\": *[_id == ^._ref][0]._type\n    }\n  }\n},\n    \"episodes\": episodes[]{\n      title,\n      \"playbackId\": mp3.asset->playbackId,\n    },\n    \"infos\": infos[]{\n  ...,\n  markDefs[]{\n    ...,\n    _type == \"internalLink\" => {\n      ...,\n      \"slug\": *[_id == ^._ref][0].slug.current,\n      \"refType\": *[_id == ^._ref][0]._type\n    }\n  }\n},\n    supports,\n    production,\n    \"credits\": credits[]{\n  \"title\": title->title,\n  \"value\": value[]{\n    _type == \"reference\" => @->{\n      _type,\n      \"name\": name,\n      \"slug\": slug.current,\n      \"link\": link,\n    },\n    _type != \"reference\" => @{\n      _type,\n      \"text\": value,\n    },\n  },\n},\n    \"gallery\": gallery[]{\n  _type,\n  _type == \"imageAlt\" => {\n  \"src\": coalesce(asset->url, \"\"),\n  \"alt\": coalesce(alt, ^.title, \"\"),\n  crop,\n  hotspot,\n},\n  _type == \"mux.video\" => {\n    \"playbackId\": coalesce(asset->playbackId, \"\"),\n  }\n},\n    links,\n    press\n  }\n": PodcastBySlugQueryResult;
    "*[_type == \"research\"][0]{\n  title,\n  \"presentation\": presentation[]{\n  ...,\n  markDefs[]{\n    ...,\n    _type == \"internalLink\" => {\n      ...,\n      \"slug\": *[_id == ^._ref][0].slug.current,\n      \"refType\": *[_id == ^._ref][0]._type\n    }\n  }\n},\n  \"notes\": notes[]{\n  ...,\n  markDefs[]{\n    ...,\n    _type == \"internalLink\" => {\n      ...,\n      \"slug\": *[_id == ^._ref][0].slug.current,\n      \"refType\": *[_id == ^._ref][0]._type\n    }\n  }\n},\n  excerptTitle,\n  \"excerpt\": excerpt[]{\n  ...,\n  markDefs[]{\n    ...,\n    _type == \"internalLink\" => {\n      ...,\n      \"slug\": *[_id == ^._ref][0].slug.current,\n      \"refType\": *[_id == ^._ref][0]._type\n    }\n  }\n}\n}": ResearchQueryResult;
    "*[_type == \"team\"][0]{\n  title,\n  \"members\": members[]->{\n    name,\n    slug,\n    role,\n    link,\n    \"presentation\": presentation[]{\n  ...,\n  markDefs[]{\n    ...,\n    _type == \"internalLink\" => {\n      ...,\n      \"slug\": *[_id == ^._ref][0].slug.current,\n      \"refType\": *[_id == ^._ref][0]._type\n    }\n  }\n}\n  }\n}": TeamQueryResult;
    "*[_type == \"calendar\"][0]{\n  title,\n  \"introduction\": introduction[]{\n  ...,\n  markDefs[]{\n    ...,\n    _type == \"internalLink\" => {\n      ...,\n      \"slug\": *[_id == ^._ref][0].slug.current,\n      \"refType\": *[_id == ^._ref][0]._type\n    }\n  }\n},\n  \n  \"seasons\": seasons[]{\n    range,\n    \"events\": events[]{\n      title,\n      description,\n      date,\n      place,\n      link,\n      \"project\": project->{\n        title,\n        \"slug\": slug.current,\n        _type,\n      }\n    }\n  }\n\n}": CalendarQueryResult;
    "*[_type == \"transmission\"][0]{\n  title,\n  \"introduction\": introduction[]{\n  ...,\n  markDefs[]{\n    ...,\n    _type == \"internalLink\" => {\n      ...,\n      \"slug\": *[_id == ^._ref][0].slug.current,\n      \"refType\": *[_id == ^._ref][0]._type\n    }\n  }\n},\n  \n  \"seasons\": seasons[]{\n    range,\n    \"events\": events[]{\n      title,\n      description,\n      date,\n      place,\n      link,\n      \"project\": project->{\n        title,\n        \"slug\": slug.current,\n        _type,\n      }\n    }\n  }\n\n}": TransmissionQueryResult;
    "*[_type == \"company\"][0]{\n  title,\n  \"presentation\": presentation[]{\n  ...,\n  markDefs[]{\n    ...,\n    _type == \"internalLink\" => {\n      ...,\n      \"slug\": *[_id == ^._ref][0].slug.current,\n      \"refType\": *[_id == ^._ref][0]._type\n    }\n  }\n},\n  \n  \"seasons\": seasons[]{\n    range,\n    \"events\": events[]{\n      title,\n      description,\n      date,\n      place,\n      link,\n      \"project\": project->{\n        title,\n        \"slug\": slug.current,\n        _type,\n      }\n    }\n  }\n\n}": CompanyQueryResult;
    "*[_type == \"legal\"]{\n  \"slug\": slug.current\n}": PagesListQueryResult;
    "*[_type == \"legal\" && slug.current == $slug][0]{\n  title,\n  \"slug\": slug.current,\n  \"content\": content[]{\n  ...,\n  markDefs[]{\n    ...,\n    _type == \"internalLink\" => {\n      ...,\n      \"slug\": *[_id == ^._ref][0].slug.current,\n      \"refType\": *[_id == ^._ref][0]._type\n    }\n  }\n}\n}": PageBySlugQueryResult;
  }
}

