/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type ShowReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "show";
};

export type PodcastReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "podcast";
};

export type ResearchReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "research";
};

export type TransmissionReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "transmission";
};

export type MemberReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "member";
};

export type CustomBlock = Array<{
  children?: Array<{
    marks?: Array<string>;
    text?: string;
    _type: "span";
    _key: string;
  }>;
  style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
  listItem?: "bullet" | "number";
  markDefs?: Array<
    | {
        href?: string;
        _type: "link";
        _key: string;
      }
    | ShowReference
    | PodcastReference
    | ResearchReference
    | TransmissionReference
    | MemberReference
  >;
  level?: number;
  _type: "block";
  _key: string;
}>;

export type Seasons = Array<{
  range: string;
  events?: Array<{
    title: string;
    description?: string;
    date?: string;
    place?: string;
    link?: string;
    project?:
      | ShowReference
      | PodcastReference
      | ResearchReference
      | TransmissionReference;
    _key: string;
  }>;
  _type: "season";
  _key: string;
}>;

export type LinksArray = Array<{
  title: string;
  subtitle?: string;
  url: string;
  _key: string;
}>;

export type JobReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "job";
};

export type Credits = Array<{
  title?: JobReference;
  value?: Array<
    | ({
        _key: string;
      } & MemberReference)
    | {
        value: CustomBlock;
        _type: "personText";
        _key: string;
      }
  >;
  _key: string;
}>;

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type ImageAlt = {
  _type: "imageAlt";
  asset?: SanityImageAssetReference;
  media?: unknown;
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  alt: string;
};

export type Favicon = {
  _type: "favicon";
  asset?: SanityImageAssetReference;
  media?: unknown;
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
};

export type Legal = {
  _id: string;
  _type: "legal";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  content: CustomBlock;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type Member = {
  _id: string;
  _type: "member";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  slug: Slug;
  role: string;
  link?: string;
  presentation?: CustomBlock;
};

export type Calendar = {
  _id: string;
  _type: "calendar";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  introduction?: CustomBlock;
  seasons?: Seasons;
};

export type Company = {
  _id: string;
  _type: "company";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  presentation: CustomBlock;
  seasons?: Seasons;
};

export type Transmission = {
  _id: string;
  _type: "transmission";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  introduction: CustomBlock;
  seasons?: Seasons;
};

export type SanityFileAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
};

export type Podcast = {
  _id: string;
  _type: "podcast";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  date: string;
  cover: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  synopsis: CustomBlock;
  episodes?: Array<{
    title: string;
    mp3?: {
      asset?: SanityFileAssetReference;
      media?: unknown;
      _type: "file";
    };
    _type: "episode";
    _key: string;
  }>;
  infos?: CustomBlock;
  supports?: string;
  production?: string;
  credits?: Credits;
  gallery?: Array<
    {
      _key: string;
    } & ImageAlt
  >;
  links?: LinksArray;
  press?: LinksArray;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type Show = {
  _id: string;
  _type: "show";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  date: string;
  cover: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  synopsis: CustomBlock;
  excerpt?: {
    type?: "text" | "image";
    text?: string;
    image?: ImageAlt;
  };
  infos?: CustomBlock;
  supports?: string;
  production?: string;
  credits?: Credits;
  gallery?: Array<
    {
      _key: string;
    } & ImageAlt
  >;
  links?: LinksArray;
  press?: LinksArray;
};

export type Job = {
  _id: string;
  _type: "job";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
};

export type Research = {
  _id: string;
  _type: "research";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  presentation: CustomBlock;
  notes?: CustomBlock;
  excerptTitle?: string;
  excerpt?: CustomBlock;
};

export type Settings = {
  _id: string;
  _type: "settings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  description: string;
  favicon?: {
    dark: Favicon;
    light: Favicon;
  };
  homeImage: ImageAlt;
  navigation: Array<{
    title: string;
    slug: Slug;
    _type: "item";
    _key: string;
  }>;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | ShowReference
  | PodcastReference
  | ResearchReference
  | TransmissionReference
  | MemberReference
  | CustomBlock
  | Seasons
  | LinksArray
  | JobReference
  | Credits
  | SanityImageAssetReference
  | ImageAlt
  | Favicon
  | Legal
  | Slug
  | Member
  | Calendar
  | Company
  | Transmission
  | SanityFileAssetReference
  | Podcast
  | SanityImageCrop
  | SanityImageHotspot
  | Show
  | Job
  | Research
  | Settings
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: src/sanity/lib/queries.ts
// Variable: footerSettingsQuery
// Query: *[_type == "settings"][0]{    title,    "navigation": navigation[]{      title,      "slug": slug.current    },    "navigationLogo": favicon.dark.asset->url,  }
export type FooterSettingsQueryResult = {
  title: string;
  navigation: Array<{
    title: string;
    slug: string;
  }>;
  navigationLogo: string | null;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: homeImageQuery
// Query: *[    _type == "settings" &&    defined(homeImage.asset->url)  ][0].homeImage{    "src": coalesce(asset->url, ""),    alt,    crop,    hotspot  }
export type HomeImageQueryResult = {
  src: string | "";
  alt: string;
  crop: SanityImageCrop | null;
  hotspot: SanityImageHotspot | null;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: showsListQuery
// Query: *[_type == "show"]{  title,  "slug": slug.current,  date,  "cover": cover{    "src": coalesce(asset->url, ""),    crop,    hotspot,  }} | order(date desc)
export type ShowsListQueryResult = Array<{
  title: string;
  slug: string;
  date: string;
  cover: {
    src: string | "";
    crop: SanityImageCrop | null;
    hotspot: SanityImageHotspot | null;
  };
}>;

// Source: src/sanity/lib/queries.ts
// Variable: showBySlugQuery
// Query: *[_type == "show" && slug.current == $slug][0]{  title,  "slug": slug.current,  date,  "cover": cover{    "src": coalesce(asset->url, ""),    crop,    hotspot,  },  synopsis,  "excerpt": excerpt{    type,    "image": image{      "src": coalesce(asset->url, ""),      crop,      hotspot,      alt    },    text  },  infos,  supports,  production,  "credits": credits[]{  "title": title->title,  "value": value[]{    _type == "reference" => @->{      _type,      "name": name,      "slug": slug.current,      "link": link,    },    _type != "reference" => @{      _type,      "text": value,    },  },},  "gallery": gallery[]{    "src": coalesce(asset->url, ""),    crop,    hotspot,    alt  },  links,  press}
export type ShowBySlugQueryResult = {
  title: string;
  slug: string;
  date: string;
  cover: {
    src: string | "";
    crop: SanityImageCrop | null;
    hotspot: SanityImageHotspot | null;
  };
  synopsis: CustomBlock;
  excerpt: {
    type: "image" | "text" | null;
    image: {
      src: string | "";
      crop: SanityImageCrop | null;
      hotspot: SanityImageHotspot | null;
      alt: string;
    } | null;
    text: string | null;
  } | null;
  infos: CustomBlock | null;
  supports: string | null;
  production: string | null;
  credits: Array<{
    title: string | null;
    value: Array<
      | {
          _type: "member";
          name: string;
          slug: string;
          link: string | null;
        }
      | {
          _type: "personText";
          text: CustomBlock;
        }
    > | null;
  }> | null;
  gallery: Array<{
    src: string | "";
    crop: SanityImageCrop | null;
    hotspot: SanityImageHotspot | null;
    alt: string;
  }> | null;
  links: LinksArray | null;
  press: LinksArray | null;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: podcastsListQuery
// Query: *[_type == "podcast"]{  title,  "slug": slug.current,  date,  "cover": cover{    "src": coalesce(asset->url, ""),    crop,    hotspot,  }} | order(date desc)
export type PodcastsListQueryResult = Array<{
  title: string;
  slug: string;
  date: string;
  cover: {
    src: string | "";
    crop: SanityImageCrop | null;
    hotspot: SanityImageHotspot | null;
  };
}>;

// Source: src/sanity/lib/queries.ts
// Variable: podcastBySlugQuery
// Query: *[_type == "podcast" && slug.current == $slug][0]{  title,  "slug": slug.current,  date,  "cover": cover{    "src": coalesce(asset->url, ""),    crop,    hotspot,  },  synopsis,  "episodes": episodes[]{    title,    "mp3": mp3.asset->url,  },  infos,  supports,  production,  "credits": credits[]{  "title": title->title,  "value": value[]{    _type == "reference" => @->{      _type,      "name": name,      "slug": slug.current,      "link": link,    },    _type != "reference" => @{      _type,      "text": value,    },  },},  "gallery": gallery[]{    "src": coalesce(asset->url, ""),    crop,    hotspot,    alt  },  links,  press}
export type PodcastBySlugQueryResult = {
  title: string;
  slug: string;
  date: string;
  cover: {
    src: string | "";
    crop: SanityImageCrop | null;
    hotspot: SanityImageHotspot | null;
  };
  synopsis: CustomBlock;
  episodes: Array<{
    title: string;
    mp3: string | null;
  }> | null;
  infos: CustomBlock | null;
  supports: string | null;
  production: string | null;
  credits: Array<{
    title: string | null;
    value: Array<
      | {
          _type: "member";
          name: string;
          slug: string;
          link: string | null;
        }
      | {
          _type: "personText";
          text: CustomBlock;
        }
    > | null;
  }> | null;
  gallery: Array<{
    src: string | "";
    crop: SanityImageCrop | null;
    hotspot: SanityImageHotspot | null;
    alt: string;
  }> | null;
  links: LinksArray | null;
  press: LinksArray | null;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '*[_type == "settings"][0]{\n    title,\n    "navigation": navigation[]{\n      title,\n      "slug": slug.current\n    },\n    "navigationLogo": favicon.dark.asset->url,\n  }': FooterSettingsQueryResult;
    '*[\n    _type == "settings" &&\n    defined(homeImage.asset->url)\n  ][0].homeImage{\n    "src": coalesce(asset->url, ""),\n    alt,\n    crop,\n    hotspot\n  }': HomeImageQueryResult;
    '*[_type == "show"]{\n  title,\n  "slug": slug.current,\n  date,\n  "cover": cover{\n    "src": coalesce(asset->url, ""),\n    crop,\n    hotspot,\n  }\n} | order(date desc)': ShowsListQueryResult;
    '*[_type == "show" && slug.current == $slug][0]{\n  title,\n  "slug": slug.current,\n  date,\n  "cover": cover{\n    "src": coalesce(asset->url, ""),\n    crop,\n    hotspot,\n  },\n  synopsis,\n  "excerpt": excerpt{\n    type,\n    "image": image{\n      "src": coalesce(asset->url, ""),\n      crop,\n      hotspot,\n      alt\n    },\n    text\n  },\n  infos,\n  supports,\n  production,\n  "credits": credits[]{\n  "title": title->title,\n  "value": value[]{\n    _type == "reference" => @->{\n      _type,\n      "name": name,\n      "slug": slug.current,\n      "link": link,\n    },\n    _type != "reference" => @{\n      _type,\n      "text": value,\n    },\n  },\n},\n  "gallery": gallery[]{\n    "src": coalesce(asset->url, ""),\n    crop,\n    hotspot,\n    alt\n  },\n  links,\n  press\n}': ShowBySlugQueryResult;
    '*[_type == "podcast"]{\n  title,\n  "slug": slug.current,\n  date,\n  "cover": cover{\n    "src": coalesce(asset->url, ""),\n    crop,\n    hotspot,\n  }\n} | order(date desc)': PodcastsListQueryResult;
    '*[_type == "podcast" && slug.current == $slug][0]{\n  title,\n  "slug": slug.current,\n  date,\n  "cover": cover{\n    "src": coalesce(asset->url, ""),\n    crop,\n    hotspot,\n  },\n  synopsis,\n  "episodes": episodes[]{\n    title,\n    "mp3": mp3.asset->url,\n  },\n  infos,\n  supports,\n  production,\n  "credits": credits[]{\n  "title": title->title,\n  "value": value[]{\n    _type == "reference" => @->{\n      _type,\n      "name": name,\n      "slug": slug.current,\n      "link": link,\n    },\n    _type != "reference" => @{\n      _type,\n      "text": value,\n    },\n  },\n},\n  "gallery": gallery[]{\n    "src": coalesce(asset->url, ""),\n    crop,\n    hotspot,\n    alt\n  },\n  links,\n  press\n}': PodcastBySlugQueryResult;
  }
}
